sudo: required

services:
  - docker

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip3 install git+https://github.com/nextstrain/cli
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update

script:
  - mkdir -p build/data/
  - cp -v example_data/zika.fasta build/data/
  - nextstrain build .
