---
# Paths in this file are relative to this pathogen repo, which may be inside
# the build container at /nextstrain/build or on the local filesystem as a
# sibling of augur, auspice, etc.

# The reference file must be in GenBank or GFF3 format.  It should contain CDS
# feature definitions to analyze for amino acid changes.
reference: config/zika_outgroup.gb

# Credentials for pulling data from fauna/rethink.  These are not provided here
# for data privacy and security reasons.  Please provide them in your
# config_local.yaml file.
credentials:
  rethink:
    host: ""
    auth_key: ""

# This defines the fields in the pipe-delimited FASTA header of each sequence.
# It is used both for downloading from fauna and processing in augur.  Fields
# may be mapped from one name in fauna to another in augur using "- from: to".
fasta_fields:
  - strain
  - virus
  - accession
  - collection_date: date
  - region
  - country
  - division
  - location: city
  - source: db
  - locus: segment
  - authors
  - url
  - title
  - journal
  - puburl: paper_url

# Parameters for filtering and subsampling step.
filter:
  exclude: config/dropped_strains.txt
  min_date: 2012
  sequences_per_category: 20
  category_fields:
    - year
    - month

timetree:
  n_iqd: 4

traits:
  # These correspond to fields in "fasta_fields" above.
  - region
  - country

auspice:
  config: config/auspice_config.json
  colors: config/colors.tsv
